#
# SPDX-License-Identifier: Apache-2.0
#
---
- name: Deploy airportchain  Blockchain infrastructure
  hosts: localhost
  vars:
    #
    # For information on these configuration options, read the documentation:
    # https://github.com/IBM-Blockchain/ansible-role-blockchain-platform-manager#example-playbook
    #
    infrastructure:
      type: docker
      docker:
        network: airport

    organizations:
      - &IBS
        msp:
          id: "IBSMSP"
          admin:
            identity: "IBSAdmin"
            secret: "IBSAdminpw"
          ibp:
            display_name: "IBS MSP"
        ca: &IBSCA
          id: "IBSCA"
          admin_identity: "admin"
          admin_secret: "adminpw"
          tls:
            enabled: false
          docker:
            name: ca.ibs.airport.com
            hostname: ca.ibs.airport.com
            port: 18050
          ibp:
            display_name: "IBS CA"
        peers:
          - &IBSPeer1
            id: "IBSPeer1"
            identity: "ibspeer1"
            secret: "ibspeer1"
            database_type: couchdb
            tls:
              enabled: false
              identity: "org1peer1tls"
              secret: "org1peer1tlspw"
            docker:
              name: peer0.ibs.airport.com
              hostname: peer0.ibs.airport.com
              port: 18051
              chaincode_port: 18052
              operations_port: 18053
              couchdb:
                name: couchdb0.ibs.airport.com
                hostname: couchdb0.ibs.airport.com
                port: 18054
            ibp:
              display_name: "ibs Peer1"
      
        nodes: "{{ playbook_dir }}/nodes/IBS"
        wallet: "{{ playbook_dir }}/wallets/IBS"
        gateways: "{{ playbook_dir }}/gateways/IBS"
    

      - &OrdererOrg
        msp:
          id: "OrdererMSP"
          admin:
            identity: "ordererAdmin"
            secret: "ordererAdminpw"
          ibp:
            display_name: "Orderer MSP"
        ca: &OrdererCA
          id: "OrdererCA"
          admin_identity: "admin"
          admin_secret: "adminpw"
          tls:
            enabled: false
          docker:
            name: ca.ibs.airport.com
            hostname: ca.ibs.airport.com
            port: 17050
          ibp:
            display_name: "Orderer CA"
        orderer: &Orderer
          id: "Orderer1"
          identity: "orderer1"
          secret: "orderer1pw"
          tls:
            enabled: false
            identity: "orderer1tls"
            secret: "orderer1tlspw"
          consortium:
            members:
              - *IBS
           
          docker:
            name: orderer.ibs.airport.com
            hostname: orderer.ibs.airport.com
            port: 17051
            operations_port: 17052
          ibp:
            display_name: "Orderer1"
            cluster_name: "OrdererCluster"
        nodes: "{{ playbook_dir }}/nodes/Orderer"
        wallet: "{{ playbook_dir }}/wallets/Orderer"
        gateways: "{{ playbook_dir }}/gateways/Orderer"
    channels:
      - &financechannel
        name: financechannel
        orderer: *Orderer
        members:
          - <<: *IBS
            committing_peers:
              - *IBSPeer1
            anchor_peers:
              - *IBSPeer1
         
    gateways:
      - name: IBS gateway
        organization:
          <<: *IBS
          gateway_peers:
            - <<: *IBSPeer1
      
  roles:
    - ibm.blockchain_platform_manager