version: '3'

services:
  restapiservice8:
    build:
      context: .
      dockerfile: Dockerfile
    image: restapiservice8
    container_name: restapiservice8
    restart: unless-stopped
    env_file: .env
  
    ports:
      - "5000:5000"
    
    networks:
      - lookupduration

networks:
  lookupduration:
    external: true
